### ISSUE TITLE
Make an attribution field for attractions (text)

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#162]

**Comment by paandahl** [comment]
Is this the same as the license box we added, or is it something you still need? If so, explain it a bit more. If not, you can close it.

**Comment by NayaMakarova** [comment]
I think it's ok. I just copy-paste the link from Wikipedia there. I think it's enough. I close the issue.

> Четверг, 10 марта 2016, 13:16 +03:00 от Preben Ludviksen notifications@github.com:
> 
> Is this the same as the license box we added, or is it something you still need? If so, explain it a bit more. If not, you can close it.
> —
> Reply to this email directly or  view it on GitHub .

## 

Regards
Anastasia Makarova
+7 (915) 344-87-67
