### ISSUE TITLE
Swiper: Part of cards are not visible on screen on iPhone 5S

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#197]
When you open anything in Swiper you can't see the name of attraction/restaurant unless you move it from its place. You can try it: Thailand-Bangkok-Attractions-Swipe and you will see only the picture of the attraction and name of it isn't visible.

**Comment by paandahl** [comment]
This is related to this one: https://github.com/prebenl/tripfinger-ios/issues/47

I have only tested on iPhone 6 so far, and it has a different screen size. It will be fixed soon hopefully.
