### ISSUE TITLE
Search: Issue with spaces in search phrase

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#199]
For example, in online mode: Thailand-Bangkok-Search-Type ''Wat Arun'' and here we have a problem: while i'm typing word ''Wat'' i see that search works and show me ''Wat Arun'' in Bangkok, but when i type a space after ''Wat'' search doesn't show me ''Wat Arun'' anymore (or any ''wat''). And like this with any name consisting of more than one word. BUT, when you're offline, you don't have this problem.

**Comment by paandahl** [comment]
Will look into it.

**Comment by paandahl** [comment]
Fixed, and available in next release.
