### ISSUE TITLE
If you click on Thailand and then attractions in offline mode, app fails. 

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#200]
If you click on Thailand, Bangkok and then attractions in offline mode, app fails. 
If you click on Thailand, and then Chiang Mai and other cities (exept Bangkok)  in offline mode, app fails.

**Comment by paandahl** [comment]
Have you downloaded Thailand?

**Comment by NayaMakarova** [comment]
Yes, I did.

Sent from Mail.Ru app for iOS

Friday 4 March 2016 05:49 +0300 from notifications@github.com  notifications@github.com:

**Comment by paandahl** [comment]
Ok, I will investigate.
