### ISSUE TITLE
Make it possible to delete cities

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#212]
I can't delete neighbourhoods in Thailand/Phuket/Bang Thao (for example).

**Comment by paandahl** [comment]
Once again - Phuket is an island, and doesn't have neighbourhoods. I will add functionality to delete cities - but first I will make sure we have a service that makes backups of our data once per week. Just in case someone accidentally deletes a big city (it can very easily happen). And we should have backups anyways

**Comment by NayaMakarova** [comment]
This button doesn't work. I still can't delete a city.

**Comment by paandahl** [comment]
For which city doesn't it work?

**Comment by NayaMakarova** [comment]
It works now, I don't understand, why it didn't work before.
