### ISSUE TITLE
Guide: App fails when navigating to any category from f.ex. Bangkok when offline

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#224]
Offline mode. Thailand - any city in Thailand - when you try to open any directory or attraction, it fails. In online mode it works.

**Comment by NayaMakarova** [comment]
With Bangkok it still fails. In any mode if you go to Bangkok, then open any neighborhood and try to go to any directory or attractions in the neighbourhood it fails. It doesn't happen with other cities that have neighbourhoods though.

**Comment by paandahl** [comment]
This was not because specific to Bangkok, but specific to cities that were downloaded (you must have downloaded Thailand). This is regardless of whether you are using the app offline or online. Keep in mind to mention if you downloaded the country or not, when filing issues.

**Comment by NayaMakarova** [comment]
Thailand was downloaded

**Comment by paandahl** [comment]
Yaya, I already fixed it :p
