### ISSUE TITLE
It's not clear where is the attraction you were looking for on the map.

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#225]
Example: Any mode. Thailand - Bangkok - open the map and try to search for ''Grand Palace''. As I understand the map shows it in the middle of the screen. In case if there aren't attractions close by, it's ok. But if there are dozen of attractions around searched one it's difficult to understand where is the attraction you were looking for. Look at the picture, this is the screen I saw after search. It's not clear at all where is the Grand Palace (I know that it's in the middle of the map, but it's annoying to click on the signs searching for it again). Maybe it will be different color of the sign or with name above it?

![image-10-03-16-08-28](https://cloud.githubusercontent.com/assets/16025697/13678280/ddac0eae-e6fe-11e5-9119-ced83ebeeaaf.png)

**Comment by paandahl** [comment]
I have made it so that it gets a green selected-ring, and that the "details"-callout with title and details-button is displayed. This helps, but is probably not good enough in the long run. However, further changes are accounted for in this issue: #213
