### ISSUE TITLE
Make sure text and image license is displayed in app

### ISSUE THREAD

**Issue by paandahl** [benwixen/tripfinger-ios#232]
- [x] Make license display view
- [x] Make it possible to add text license to regions in admin
- [x] Make it possible to add text license to sections in admin
- [x] Make sure that text license is inherited from parent if not specified
- [x] Make sure image and text license is possible to view for listings as well

**Comment by NayaMakarova** [comment]
'' Make sure that text license is inherited from parent if not specified ''. I didn't understand that. The rest works.

**Comment by paandahl** [comment]
It means that if you f.ex. have the region Moscow, and you add a license by clicking on metadata at the top. Then you add f.ex. a section "History" without adding license information. If you view History in the app, and click on the license-button, you should see the same license text as specified for Moscow. It's inherited.
