### ISSUE TITLE
Not all the sights you liked show up on the map when it's zoomed out.

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#234]
As example Chiang Mai area: there are no red markers in that area when it's zoomed out.
![image-17-03-16-02-33-1](https://cloud.githubusercontent.com/assets/16025697/13844996/3bfb22d4-ec4e-11e5-8280-67f185d9c44c.png)

![image-17-03-16-02-33](https://cloud.githubusercontent.com/assets/16025697/13845010/42bb87e4-ec4e-11e5-8df7-3c2584f4d3c0.png)

**Comment by paandahl** [comment]
I was not able to reproduce this issue, but I fixed something else relating to likes, so I MIGHT have fixed it.

If you are able to make it happen again, you need to write the exact procedure. After you did it, delete the app, re-install, and make sure that following the procedure will work for me.

So, f.ex something like this:
1. Open freshly installed app.
2. Click on Chiang Mai.
3. Click on Attractions.
4. Swipe left on everything, but swipe right on attraction X.
5. Go back to Thailand.
6. Click on map.
7. See that attraction is not displayed with a red ring.

I know it's a lot of work, but some issues are hard to reproduce.

**Comment by paandahl** [comment]
But wait until build 18 is released, since I MIGHT have fixed it.
