### ISSUE TITLE
Change the label to destinations

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#239]
For example, ''Cape Panwa'' isn't a city in Phuket, it's region in Phuket.

**Comment by NayaMakarova** [comment]
Now will be a stupid question: can I see that it's changed?

**Comment by paandahl** [comment]
<img width="375" alt="screen shot 2016-03-28 at 11 13 45" src="https://cloud.githubusercontent.com/assets/44539/14071414/2f26c9ce-f4d6-11e5-922b-49b28773396f.png">

Just look at the label over "Cape Panwa".
