### ISSUE TITLE
Error in country lists

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#248]
When Thailand is downloaded and you go to the first page in online mode, Thailand isn't displayed there.
![image-20-03-16-11-00-1](https://cloud.githubusercontent.com/assets/16025697/13906768/bcf42db0-eeef-11e5-95d0-800b7125b34e.png)
But when you refresh the page, Thailand appears, but Russia disappears.
![image-20-03-16-11-00 2](https://cloud.githubusercontent.com/assets/16025697/13906774/d831d500-eeef-11e5-8576-9d977c034895.png)

**Comment by paandahl** [comment]
I wasn't able to reproduce the exact same error as you had, but I fixed a bug in the code that generated the list of countries, and it's likely to have been caused by that one.
