### ISSUE TITLE
Bold text is not displayed as bold in the texts in the app.

### ISSUE THREAD

**Issue by NayaMakarova** [benwixen/tripfinger-ios#270]
For example ''Food'' should be bold  in the Food article of Almaty.
![slack for ios upload 2](https://cloud.githubusercontent.com/assets/16025697/14136197/36df0754-f66a-11e5-9cbd-f7f7ce63e2db.png)

**Comment by NayaMakarova** [comment]
It still doesn't work. Compare for ex. shopping section in Georgia with an admin text.

**Comment by paandahl** [comment]
Build24 is not released yet..
